from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional, List


class HumanFeedback(BaseModel):
    """
    Represents a human-in-the-loop correction or validation
    for a given query and document context.
    """

    id: Optional[str] = None

    query: str = Field(..., description="Original user query")

    document_ids: List[str] = Field(
        ...,
        description="Documents this feedback applies to"
    )

    original_answer: str = Field(
        ...,
        description="Answer generated by the system"
    )

    corrected_answer: str = Field(
        ...,
        description="Human-corrected or approved answer"
    )

    notes: Optional[str] = Field(
        None,
        description="Optional human explanation or notes"
    )

    created_at: datetime = Field(
        default_factory=datetime.utcnow
    )

    approved: bool = Field(
        True,
        description="Whether this correction is approved for reuse"
    )
